#!/usr/bin/env python

import sys

# Symmetrize results
fwd, rev = open(sys.argv[1]), open(sys.argv[2])
fwd_aligns = [set([tuple(map(int, x.split("-"))) for x in a.strip().split()]) for a in fwd]
rev_aligns = [set([tuple(map(int, reversed(x.split("-")))) for x in a.strip().split()]) for a in rev]
inter_aligns = [x | y for (x, y) in zip(fwd_aligns, rev_aligns)]
for a in inter_aligns:
    for (i, j) in a:
        sys.stdout.write('%i-%i ' % (i, j))
    sys.stdout.write('\n')
